name: .NET Core Publish

on:
  push:
    branches: [ master ]

env:
  AZURE_WEBAPP_NAME: BeezyBackendTestApi20200425164353    # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: 'beezybackendwebapp'      # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '3.1.101'           # set this to the dot net version to use

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }} 
    
    - name: Install dependencies
      run: dotnet restore
    
      # Run dotnet build, test and publish
    - name: Build
      run: dotnet build --configuration Release --no-restore
    
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    
    - name: Publish
      run: dotnet test --no-restore --verbosity normal 
          
    # Deploy to Azure Web apps
    - name: 'Run Azure webapp deploy action using publish profile credentials'
      uses: azure/webapps-deploy@v2
      with: 
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE  }} # Define secret variable in repository settings as per action documentation
        package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}'
